In [ ]:
pip install colabCode


In [ ]:
# Install the Google Colaboratory library
!pip install google-colab


In [ ]:
print('remember to ask Tm on how to install the google-colab')

In [ ]:
from colabCode import ColabCode

In [ ]:
import numpy as np

In [ ]:
import IPython
import numpy as np
import tables
print(np.__version__)
print(dir(np))
print(IPython)


In [ ]:
#Attributes of arrays: Determining the size, shape, memory 
#consumption, and data types of arrays
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)


In [47]:
#LISTS
#a stardard mutable multi-element container in Python
L = list(range(10))
print(L)
type(L[0])
# list of strings >integers become strings
L2 = [str(c) for c in L]
print(L2)
print(L2[0])
#heterogeneous lists
L3 = [True, "2", 3.0, 4]
print([type(item) for item in L3])
#fixed-type arrays in Python
import array
L = list(range(10))
A = array.array('i', L)
print(A)
#array.array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) i type code indicating the contents are integers
#NumPy arrays: the efficient ndarray creating arrays from Python lists
import numpy as np
#integer array
np.array([1, 4, 2, 5, 3])
print(np.array([1, 4, 2, 5, 3]))
#NumPy is constrained to arrays that all contain the same type
#If types do not match, NumPy will upcast if possible
np.array([3.14, 4, 2, 3])
print(np.array([3.14, 4, 2, 3]))
#explicitly set the data type using the dtype keyword
np.array([1, 2, 3, 4], dtype='float32')
#print(np.array([1, 2, 3, 4], dtype='float32')) 
#unlike Python lists, NumPy arrays can explicitly be multidimensional
#nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])
#print(np.array([range(i, i + 3) for i in [2, 4, 6]]))
#creating arrays from scratch
#Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)
print(np.zeros(10, dtype=int))
#Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)
#print(np.ones((3, 5), dtype=float))
#Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)
#print(np.full((3, 5), 3.14))
#Create an array filled with a linear sequence
#Starting at 0, ending at 20, stepping by 2
#(this is similar to the built-in range() function)
np.arange(0, 20, 2)
#print(np.arange(0, 20, 2))
#Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)
#print(np.linspace(0, 1, 5))
#Create a 3x3 array of uniformly distributed
#random values between 0 and 1
np.random.random((3, 3))
#print(np.random.random((3, 3)))
#Create a 3x3 array of normally distributed random values
#with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))
#print(np.random.normal(0, 1, (3, 3)))
#Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))
#print(np.random.randint(0, 10, (3, 3)))
#Create a 3x3 identity matrix
np.eye(3)
#print(np.eye(3))
#Create an uninitialized array of three integers
#The values will be whatever happens to already exist at that
#memory location
np.empty(3)
#print(np.empty(3))















[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
0
[<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>]
array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
[1 4 2 5 3]
[3.14 4.   2.   3.  ]
[0 0 0 0 0 0 0 0 0 0]


array([2.47032823e-323, 6.36598737e-314, 1.90979621e-313])